config/routes.rb
ArtisanEngine::Application.routes.draw do
  root to: 'visit/pages#home'
  
  get '/develop' => 'develop/develop#interface'
  namespace :develop do
    resources :frames do
      resources :settings
    end
    resources :artisans
  end
  
  get '/manage' => 'manage/manage#interface'
  namespace :manage do
    resources :goods do
      resources :options
      resources :variants
      resources :image_attachers
      resources :images
    end
    resources :display_cases do
      resources :collects
    end
    resources :page_collections do
      resources :page_collects
    end
    resources :images do
      get 'cropping/:priority' => 'images#crop', as: 'cropping'
    end
    resources :pages
    post      'page/preview' => 'pages#preview', as: 'preview_page'
    resource  :blog do
      resources :posts
    end
    resources :tags
    resources :orders do
      resources :fulfillments
    end
    resources :patrons
    resources :promotions
  end
  
  scope :module => :visit do
    resources :pages, only: [ :show ]
    resources :page_collections, only: [ :show ]
    
    resource  :blog, only: [ :show ] do
      resources :posts, only: [ :index ]
      get '/:year(/:month)' => 'posts#index', as: 'by_date'
    end
    get '/blog/:year/:month/:id' => 'posts#show',  as: 'blog_post'
    
    resources :goods, only: [ :show ]
    resources :display_cases, path: 'collections'
    
    post '/subscribe' => 'patrons#subscribe'
    post '/donations' => 'mail_forms#donations'
    post '/press'     => 'mail_forms#press'
    post '/wholesale' => 'mail_forms#wholesale'
    post '/contact'   => 'mail_forms#contact'
    
    post '/apply_promotion' => 'promotions#apply', as: 'apply_promotion'
    
    get '/order'     => 'orders#new',    as: 'new_order'
    get '/checkout'  => 'orders#edit',   as: 'checkout'
    put '/checkout'  => 'orders#update',  as: 'checkout'
    get '/order/confirm' => 'orders#confirm', as: 'confirm'
    get '/order/cancel'  => 'orders#cancel',  as: 'cancel'
    get  '/paypal'   => 'orders#paypal',           as: 'paypal'
    post '/ipns'     => 'order_transactions#ipns', as: 'ipns'
    
    get '/update_state_select' => 'orders#update_state_select', as: 'update_state_select'
    
    resources :line_items do
      post 'update_quantities', on: :collection, as: 'quantities'
    end
  end
  
  # Recreate Devise routes from scratch and override Sessions Controller.
  devise_for :artisans, controllers: { sessions: 'manage/sessions' }, skip: [ :sessions ] do
    get  '/manage/sign_in'  => 'manage/sessions#new',     as: 'new_artisan_session'
    post '/manage/sign_in'  => 'manage/sessions#create',  as: 'artisan_session'
    get  '/manage/sign_out' => 'manage/sessions#destroy', as: 'destroy_artisan_session'
  end
  
  devise_for :engineers, controllers: { sessions: 'develop/sessions' }, skip: [ :sessions ] do
    get  '/develop/sign_in'  => 'develop/sessions#new',     as: 'new_engineer_session'
    post '/develop/sign_in'  => 'develop/sessions#create',  as: 'engineer_session'
    get  '/develop/sign_out' => 'develop/sessions#destroy', as: 'destroy_engineer_session'
  end
end

app/models/blog.rb
# Each frame has a blog. It basically functions as a wrapper for posts.
class Blog < ActiveRecord::Base
  attr_accessible :name
  
  # ------------------------------------------------------------------
  # Associations
  
  belongs_to :frame
  has_many   :posts, dependent: :destroy
  
  # ------------------------------------------------------------------
  # Validations
  
  validates_presence_of :name, :frame
end

app/controllers/visit/blogs_controller.rb
module Visit
  class BlogsController < Visit::VisitController
    layout :blog_or_visit
    
    expose( :blog )        { current_frame.blog }
    expose( :tags )        { current_frame.tags }
    expose( :recent_post ) { blog.posts.order( "created_at DESC" ).first }
    
    # ------------------------------------------------------------------
    private
    
    def blog_or_visit
      template_exists?( "layouts/blog" ) ? 'blog' : 'visit'
    end
  end
end

app/views/layouts/blog/_date_navigation.html.haml
%h3.sort-heading View by Date
%nav#dates
	~#%li= link_to 'December 2011', by_date_blog_path( year: 2011, month: 12 )
	~#%li= link_to 'November 2011', by_date_blog_path( year: 2011, month: 11 )
	~#%li= link_to 'October 2011', by_date_blog_path( year: 2011, month: 10 )
	%li= link_to 'September 2011', by_date_blog_path( year: 2011, month: 9 )
	%li= link_to 'August 2011', by_date_blog_path( year: 2011, month: 8 )
	%li= link_to 'July 2011', by_date_blog_path( year: 2011, month: 7 )
	%li= link_to 'June 2011', by_date_blog_path( year: 2011, month: 6 )
	%li= link_to 'May 2011', by_date_blog_path( year: 2011, month: 5 )
	%li= link_to 'April 2011', by_date_blog_path( year: 2011, month: 4 )
	%li= link_to 'March 2011', by_date_blog_path( year: 2011, month: 3 )
	%li= link_to 'February 2011', by_date_blog_path( year: 2011, month: 2 )
	%li= link_to 'January 2011', by_date_blog_path( year: 2011, month: 1 )
	
	%li= link_to 'December 2010', by_date_blog_path( year: 2010, month: 12 )
	%li= link_to 'November 2010', by_date_blog_path( year: 2010, month: 11 )
	%li= link_to 'October 2010', by_date_blog_path( year: 2010, month: 10 )
	%li= link_to 'September 2010', by_date_blog_path( year: 2010, month: 9 )
	%li= link_to 'August 2010', by_date_blog_path( year: 2010, month: 8 )
	%li= link_to 'July 2010', by_date_blog_path( year: 2010, month: 7 )
	%li= link_to 'June 2010', by_date_blog_path( year: 2010, month: 6 )
	%li= link_to 'May 2010', by_date_blog_path( year: 2010, month: 5 )
	%li= link_to 'April 2010', by_date_blog_path( year: 2010, month: 4 )
	%li= link_to 'March 2010', by_date_blog_path( year: 2010, month: 3 )
	%li= link_to 'February 2010', by_date_blog_path( year: 2010, month: 2 )
	%li= link_to 'January 2010', by_date_blog_path( year: 2010, month: 1 )
	
	%li= link_to 'December 2009', by_date_blog_path( year: 2009, month: 12 )
	%li= link_to 'November 2009', by_date_blog_path( year: 2009, month: 11 )
	%li= link_to 'October 2009', by_date_blog_path( year: 2009, month: 10 )
	%li= link_to 'September 2009', by_date_blog_path( year: 2009, month: 9 )
	%li= link_to 'August 2009', by_date_blog_path( year: 2009, month: 8 )
	%li= link_to 'July 2009', by_date_blog_path( year: 2009, month: 7 )
	%li= link_to 'June 2009', by_date_blog_path( year: 2009, month: 6 )
	%li= link_to 'May 2009', by_date_blog_path( year: 2009, month: 5 )
	%li= link_to 'April 2009', by_date_blog_path( year: 2009, month: 4 )
	%li= link_to 'March 2009', by_date_blog_path( year: 2009, month: 3 )
	%li= link_to 'February 2009', by_date_blog_path( year: 2009, month: 2 )
	%li= link_to 'January 2009', by_date_blog_path( year: 2009, month: 1 )
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	

app/views/layouts/blog/_sidebar.html.haml
%section#sidebar
	= render 'layouts/blog/tag_navigation'
	= render 'layouts/blog/date_navigation'

app/views/layouts/blog/_tag_navigation.html.haml
%h3.sort-heading View by Topic
%nav#tags
	- for tag in tags
		%li= link_to tag.name, blog_posts_path( tagged_with: tag.name )